"""
Stub typings for boto3
"""
from typing import Dict, Any, List, Optional, Union

class S3Client:
    def upload_file(self, Filename: str, Bucket: str, Key: str, ExtraArgs: Optional[Dict[str, Any]] = None) -> None: ...
    def download_file(self, Bucket: str, Key: str, Filename: str) -> None: ...
    def get_paginator(self, operation_name: str) -> Any: ...

class EC2Client:
    def run_instances(self, **kwargs: Any) -> Dict[str, Any]: ...
    def stop_instances(self, InstanceIds: List[str]) -> Dict[str, Any]: ...
    def describe_instances(self, InstanceIds: List[str]) -> Dict[str, Any]: ...

class BatchClient:
    def submit_job(self, **kwargs: Any) -> Dict[str, Any]: ...
    def describe_jobs(self, jobs: List[str]) -> Dict[str, Any]: ...

def client(service_name: str, **kwargs: Any) -> Union[S3Client, EC2Client, BatchClient]: ...
