"""
Stub typings for noise module
"""

from typing import Any, Optional

def snoise2(x: float, y: float, octaves: int = 1, persistence: float = 0.5, lacunarity: float = 2.0, repeatx: Optional[int] = None, repeaty: Optional[int] = None, base: int = 0) -> float: ...
def snoise3(x: float, y: float, z: float, octaves: int = 1, persistence: float = 0.5, lacunarity: float = 2.0, repeatx: Optional[int] = None, repeaty: Optional[int] = None, repeatz: Optional[int] = None, base: int = 0) -> float: ...
def snoise4(x: float, y: float, z: float, w: float, octaves: int = 1, persistence: float = 0.5, lacunarity: float = 2.0, repeatx: Optional[int] = None, repeaty: Optional[int] = None, repeatz: Optional[int] = None, repeatw: Optional[int] = None, base: int = 0) -> float: ...
def pnoise1(x: float, octaves: int = 1, persistence: float = 0.5, lacunarity: float = 2.0, repeat: Optional[int] = None, base: int = 0) -> float: ...
def pnoise2(x: float, y: float, octaves: int = 1, persistence: float = 0.5, lacunarity: float = 2.0, repeatx: Optional[int] = None, repeaty: Optional[int] = None, base: int = 0) -> float: ...
def pnoise3(x: float, y: float, z: float, octaves: int = 1, persistence: float = 0.5, lacunarity: float = 2.0, repeatx: Optional[int] = None, repeaty: Optional[int] = None, repeatz: Optional[int] = None, base: int = 0) -> float: ...
