"""
Stub typings for azure.storage.blob
"""
from typing import Dict, Any, List, Optional, Union, Iterator, AsyncIterator, IO

class BlobClient:
    def __init__(self, account_url: str, container_name: str, blob_name: str, credential: Any = None) -> None: ...
    @property
    def url(self) -> str: ...
    def upload_blob(self, data: Union[bytes, str, IO[bytes]], **kwargs: Any) -> Dict[str, Any]: ...
    def download_blob(self) -> Any: ...

class ContainerClient:
    def __init__(self, account_url: str, container_name: str, credential: Any = None) -> None: ...
    def list_blobs(self, name_starts_with: Optional[str] = None) -> Union[Iterator[Any], AsyncIterator[Any]]: ...

class BlobServiceClient:
    def __init__(self, account_url: str, credential: Any = None) -> None: ...
    @classmethod
    def from_connection_string(cls, conn_str: str) -> "BlobServiceClient": ...
    def get_blob_client(self, container: str, blob: str) -> BlobClient: ...
    def get_container_client(self, container: str) -> ContainerClient: ...
